coding_task:
  description: >
    Write python code to complete the given assignment: {assignment}. Always run the code to determine the output instead of assuming 
    what the output is.
  expected_output: >
    A text file that includes the code itself, along with the output of the code.
  agent: coder
  output_file: output/code_and_output.txt
